# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swifty-companion' do
	pod 'SwiftyJSON', '~> 4.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swifty-companion
pod 'Alamofire', '~> 5.4'

end
